#alpine setup
#commands used are based on /bin/sh
FROM node:alpine AS BUILD
#ARG NODE_ENV=production
#ENV NODE_ENV ${NODE_ENV}

WORKDIR /monoapp

COPY . .
COPY package.json ./
COPY package-lock.json ./

RUN npm install

RUN npm run build


FROM nginx:1.23-alpine AS HOSTING
#ARG NODE_ENV=production
#ENV NODE_ENV ${NODE_ENV}

WORKDIR /
RUN mkdir /initApp
COPY /build-config/entrypoint.sh /initApp
COPY /build-config/nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=BUILD monoapp/dist .

#EXPOSE 443
EXPOSE 80
WORKDIR /
USER root
RUN chmod +x ./initApp/entrypoint.sh
CMD /bin/sh ./initApp/entrypoint.sh